//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoyectoGuiasTuristicos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGuiasTuristicosEntities : DbContext
    {
        public dbGuiasTuristicosEntities()
            : base("name=dbGuiasTuristicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Museo> Museo { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<ReservaOrganizaMuseo> ReservaOrganizaMuseo { get; set; }
        public virtual DbSet<ReservaOrganizaRuta> ReservaOrganizaRuta { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Valoracion> Valoracion { get; set; }
    }
}
